import { BINARY_NAME, GITHUB_REPO_URL } from "./repo"

export const DEVSY_GIT_REPOSITORY = GITHUB_REPO_URL

export const DEFAULT_STATIC_COMMAND_CONFIG = {
  streamResponse: false,
  debug: false,
} as const
/** placeholder for arbitrary additional flags */
export const WORKSPACE_COMMAND_ADDITIONAL_FLAGS_KEY = "additionalFlags"

export const DEVSY_BINARY = `bin/${BINARY_NAME}`
export const DEVSY_COMMAND_LIST = "list"
export const DEVSY_COMMAND_STATUS = "status"
export const DEVSY_COMMAND_UP = "up"
export const DEVSY_COMMAND_STOP = "stop"
export const DEVSY_COMMAND_BUILD = "build"
export const DEVSY_COMMAND_DELETE = "delete"
export const DEVSY_COMMAND_PROVIDER = "provider"
export const DEVSY_COMMAND_IDE = "ide"
export const DEVSY_COMMAND_PRO = "pro"
export const DEVSY_COMMAND_OPTIONS = "options"
export const DEVSY_COMMAND_SET_OPTIONS = "set-options"
export const DEVSY_COMMAND_USE = "use"
export const DEVSY_COMMAND_ADD = "add"
export const DEVSY_COMMAND_HELPER = "helper"
export const DEVSY_COMMAND_UPDATE = "update"
export const DEVSY_COMMAND_RENAME = "rename"
export const DEVSY_COMMAND_CONTEXT = "context"
export const DEVSY_COMMAND_LOGIN = "login"
export const DEVSY_COMMAND_IMPORT_WORKSPACE = "import-workspace"
export const DEVSY_COMMAND_GET_WORKSPACE_NAME = "get-workspace-name"
export const DEVSY_COMMAND_GET_WORKSPACE_UID = "get-workspace-uid"
export const DEVSY_COMMAND_GET_WORKSPACE_CONFIG = "get-workspace-config"
export const DEVSY_COMMAND_GET_PROVIDER_NAME = "get-provider-name"
export const DEVSY_COMMAND_GET_PRO_NAME = "get-pro-name"
export const DEVSY_COMMAND_CHECK_PROVIDER_UPDATE = "check-provider-update"
export const DEVSY_COMMAND_TROUBLESHOOT = "troubleshoot"
export const DEVSY_FLAG_JSON_LOG_OUTPUT = "--log-output=json"
export const DEVSY_FLAG_JSON_OUTPUT = "--output=json"
export const DEVSY_FLAG_OPTION = "--option"
export const DEVSY_FLAG_FORCE = "--force"
export const DEVSY_FLAG_FORCE_BUILD = "--force-build"
export const DEVSY_FLAG_RECREATE = "--recreate"
export const DEVSY_FLAG_RESET = "--reset"
export const DEVSY_FLAG_IDE = "--ide"
export const DEVSY_FLAG_PROVIDER = "--provider"
export const DEVSY_FLAG_PROVIDER_OPTION = "--provider-option"
export const DEVSY_FLAG_ACCESS_KEY = "--access-key"
export const DEVSY_FLAG_PREBUILD_REPOSITORY = "--prebuild-repository"
export const DEVSY_FLAG_ID = "--id"
export const DEVSY_FLAG_SOURCE = "--source"
export const DEVSY_FLAG_DEBUG = "--debug"
export const DEVSY_FLAG_USE = "--use"
export const DEVSY_FLAG_NAME = "--name"
export const DEVSY_FLAG_SINGLE_MACHINE = "--single-machine"
export const DEVSY_FLAG_DRY = "--dry"
export const DEVSY_FLAG_RECONFIGURE = "--reconfigure"
export const DEVSY_FLAG_SKIP_REQUIRED = "--skip-required"
export const DEVSY_FLAG_TIMEOUT = "--timeout"
export const DEVSY_FLAG_DEVCONTAINER_PATH = "--devcontainer-path"
export const DEVSY_FLAG_WORKSPACE_ID = "--workspace-id"
export const DEVSY_FLAG_WORKSPACE_UID = "--workspace-uid"
export const DEVSY_FLAG_WORKSPACE_PROJECT = "--workspace-project"
export const DEVSY_FLAG_LOGIN = "--login"
export const DEVSY_FLAG_HOST = "--host"
export const DEVSY_FLAG_INSTANCE = "--instance"
export const DEVSY_FLAG_PROJECT = "--project"
export const DEVSY_FLAG_SKIP_PRO = "--skip-pro"
export const DEVSY_FLAG_DOTFILES = "--dotfiles"
export const DEVSY_FLAG_GIT_SIGNING_KEY = "--git-ssh-signing-key"
export const DEVSY_FLAG_FORCE_BROWSER = "--force-browser"

export const DEVSY_UI_ENV_VAR = "DEVSY_UI"
export const DEVSY_ADDITIONAL_ENV_VARS = "DEVSY_ADDITIONAL_ENV_VARS"
