changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - devsy-app[bot]
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Infrastructure
      labels:
        - ci
        - infrastructure
    - title: Other Changes
      labels:
        - "*"
