version: 2
project_name: devsy
release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
builds:
  - id: devsy
    hooks:
      pre:
        - sh -c 'CGO_ENABLED=1 go test $(go list ./... | grep -v -e /test -e /e2e) -race -short -coverprofile=dist/profile.out -covermode=atomic'
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    binary: devsy-{{ .Os }}-{{ .Arch }}
    overrides:
      - goos: linux
        goarch: amd64
        ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
        tags:
          - netgo
          - osusergo
      - goos: linux
        goarch: arm64
        ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
        tags:
          - netgo
          - osusergo
    ldflags: -s -w -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
    env:
      - CGO_ENABLED=0

  - id: devsy-linux
    hooks:
      pre:
        - sh -c 'CGO_ENABLED=1 go test $(go list ./... | grep -v -e /test -e /e2e) -race -short -coverprofile=dist/profile.out -covermode=atomic'
    goos: [linux]
    goarch: [amd64, arm64]
    binary: devsy-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
    env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - osusergo

  - id: devsy-darwin
    hooks:
      pre:
        - sh -c 'go test $(go list ./... | grep -v -e /test -e /e2e) -race -short -coverprofile=dist/profile.out -covermode=atomic'
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: devsy-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
    env:
      - CGO_ENABLED=0

  - id: devsy-windows
    goos: [windows]
    goarch: [amd64, arm64]
    binary: devsy-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
    env:
      - CGO_ENABLED=0

  - id: devsy-dev
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    binary: devsy-{{ .Os }}-{{ .Arch }}
    ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
    env:
      - CGO_ENABLED=0
    tags:
      - netgo
      - osusergo

  - id: devsy-pro-dev
    goos: [linux]
    goarch: [amd64]
    binary: devsy-{{ .Os }}-{{ .Arch }}-pro
    ldflags: -s -w -extldflags '-static' -X main.build={{ .Env.DEVSY_CLI_VERSION }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X github.com/devsy-org/devsy/pkg/version.version={{ .Env.DEVSY_CLI_VERSION }} -X github.com/devsy-org/devsy/pkg/telemetry/analytics.posthogAPIKey={{ envOrDefault "DEVSY_POSTHOG_API_KEY" "" }}
    env:
      - CGO_ENABLED=0
    tags:
      - profile
      - osusergo
      - netgo
    hooks:
      post:
        - cmd: kubectl -n "{{ .Env.DEVSY_PRO_NS | default "default" }}" cp --no-preserve=true dist/devsy-pro_linux_amd64_v1/devsy-{{ .Os }}-{{ .Arch }}-pro "$(kubectl -n "{{ .Env.DEVSY_PRO_NS | default "default" }}" get pods -l app=devsy -o jsonpath="{.items[0].metadata.name}")":/usr/local/bin/devsy
          env:
            - DEVSY_PRO_NS={{ .Env.DEVSY_PRO_NS | default "default" }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
report_sizes: true
