package names_test

import (
	"testing"

	"github.com/devsy-org/devsy/pkg/flags/names"
)

var wireNames = []struct {
	got  string
	want string
}{
	{names.DevContainer, "devcontainer"},
	{names.DevContainerImage, "devcontainer-image"},
	{names.DevContainerPath, "devcontainer-path"},
	{names.DevContainerID, "devcontainer-id"},
	{names.DevContainerOverlay, "devcontainer-overlay"},
	{names.FallbackImage, "fallback-image"},
	{names.Features, "features"},
	{names.IDLabel, "id-label"},
	{names.UserEnvProbe, "user-env-probe"},
	{names.GPUAvailability, "gpu-availability"},
	{names.UpdateRemoteUserUID, "update-remote-user-uid"},
	{names.ContainerDataFolder, "container-data-folder"},
	{names.MountWorkspaceGitRoot, "mount-workspace-git-root"},
	{names.ContainerUser, "container-user"},
	{names.RemoteUser, "remote-user"},
	{names.SSHConfigure, "ssh-configure"},
	{names.SSHGPGForwarding, "ssh-gpg-forwarding"},
	{names.SSHConfig, "ssh-config"},
	{names.SSHTunnel, "ssh-tunnel"},
	{names.AgentForwarding, "agent-forwarding"},
	{names.ReuseSSHAuthSock, "reuse-ssh-auth-sock"},
	{names.Stdio, "stdio"},
	{names.StartServices, "start-services"},
	{names.SSHKeepAliveInterval, "ssh-keepalive-interval"},
	{names.ForwardPorts, "forward-ports"},
	{names.ReverseForwardPorts, "reverse-forward-ports"},
	{names.SendEnv, "send-env"},
	{names.SetEnv, "set-env"},
	{names.ForwardPortsTimeout, "forward-ports-timeout"},
	{names.TermMode, "term-mode"},
	{names.InstallTerminfo, "install-terminfo"},
	{names.TrackActivity, "track-activity"},
	{names.Dotfiles, "dotfiles"},
	{names.DotfilesScript, "dotfiles-script"},
	{names.DotfilesTargetPath, "dotfiles-target-path"},
	{names.DotfilesScriptEnv, "dotfiles-script-env"},
	{names.DotfilesScriptEnvFile, "dotfiles-script-env-file"},
	{names.DotfilesRepo, "dotfiles-repo"},
	{names.GitCloneStrategy, "git-clone-strategy"},
	{names.GitRecurseSubmodules, "git-recurse-submodules"},
	{names.GitLFSMode, "git-lfs-mode"},
	{names.GitSSHSigningKey, "git-ssh-signing-key"},
	{names.SkipPostCreate, "skip-post-create"},
	{names.SkipPostStart, "skip-post-start"},
	{names.SkipPostAttach, "skip-post-attach"},
	{names.SkipNonBlockingCommands, "skip-non-blocking-commands"},
	{names.SkipHostRequirements, "skip-host-requirements"},
	{names.TerminalColumns, "terminal-columns"},
	{names.TerminalRows, "terminal-rows"},
	{names.ID, "id"},
	{names.Machine, "machine"},
	{names.Source, "source"},
	{names.ProviderOption, "provider-option"},
	{names.Reconfigure, "reconfigure"},
	{names.Prebuild, "prebuild"},
	{names.Pull, "pull"},
	{names.NoCache, "no-cache"},
	{names.Recreate, "recreate"},
	{names.Reset, "reset"},
	{names.PrebuildRepo, "prebuild-repo"},
	{names.WorkspaceEnv, "workspace-env"},
	{names.WorkspaceEnvFile, "workspace-env-file"},
	{names.SecretsFile, "secrets-file"},
	{names.FeatureSecretsFile, "feature-secrets-file"},
	{names.InitEnv, "init-env"},
	{names.DisableDaemon, "disable-daemon"},
	{names.CacheFrom, "cache-from"},
	{names.WorkspaceMountConsistency, "workspace-mount-consistency"},
	{names.Mount, "mount"},
	{names.Platform, "platform"},
	{names.PullFromInsideContainer, "pull-from-inside-container"},
	{names.WorkspaceFolder, "workspace-folder"},
	{names.IgnoreNotFound, "ignore-not-found"},
	{names.GracePeriod, "grace-period"},
	{names.Force, "force"},
	{names.RemoveVolumes, "remove-volumes"},
	{names.IDE, "ide"},
	{names.IDEOption, "ide-option"},
	{names.IDELaunch, "ide-launch"},
	{names.Option, "option"},
	{names.Userns, "userns"},
	{names.UIDMap, "uidmap"},
	{names.GIDMap, "gidmap"},
	{names.ContainerID, "container-id"},
	{names.DockerPath, "docker-path"},
	{names.RemoteEnv, "remote-env"},
	{names.ContainerWorkspaceInfo, "container-workspace-info"},
	{names.ChownWorkspace, "chown-workspace"},
	{names.StreamMounts, "stream-mounts"},
	{names.InjectGitCredentials, "inject-git-credentials"},
	{names.AccessKey, "access-key"},
	{names.WorkspaceHost, "workspace-host"},
	{names.PlatformHost, "platform-host"},
	{names.Repository, "repository"},
	{names.StrictHostKeyChecking, "strict-host-key-checking"},
	{names.InstallScript, "install-script"},
	{names.SkipPro, "skip-pro"},
	{names.ContainerStatus, "container-status"},
	{names.WorkspaceID, "workspace-id"},
	{names.MachineID, "machine-id"},
	{names.MachineReuse, "machine-reuse"},
	{names.ProviderID, "provider-id"},
	{names.ProviderReuse, "provider-reuse"},
	{names.Data, "data"},
	{names.SkipDelete, "skip-delete"},
	{names.Tag, "tag"},
	{names.SkipPush, "skip-push"},
	{names.Push, "push"},
	{names.Label, "label"},
	{names.Output, "output"},
	{names.ExperimentalLockfile, "experimental-lockfile"},
	{names.ImageName, "image-name"},
	{names.NoBuild, "no-build"},
	{names.ForceBuild, "force-build"},
	{names.ForceInternalBuildKit, "force-internal-buildkit"},
	{names.DaemonInterval, "daemon-interval"},
	{names.ForceDockerless, "force-dockerless"},
	{names.Debug, "debug"},
	{names.Command, "command"},
	{names.Context, "context"},
	{names.User, "user"},
	{names.Workdir, "workdir"},
	{names.Home, "home"},
	{names.LogOutput, "log-output"},
	{names.LogFormat, "log-format"},
	{names.ResultFormat, "result-format"},
	{names.SetupInfo, "setup-info"},
	{names.SecretsEnv, "secrets-env"},
	{names.OwnerTrust, "ownertrust"},
	{names.SocketPath, "socketpath"},
	{names.GitKey, "gitkey"},
	{names.ShutdownAction, "shutdown-action"},
	{names.Timeout, "timeout"},
	{names.Flavor, "flavor"},
	{names.Verbose, "verbose"},
	{names.Quiet, "quiet"},
	{names.Owner, "owner"},
	{names.AgentDir, "agent-dir"},
	{names.UID, "uid"},
	{names.OpenBrowser, "open-browser"},
	{names.InheritListener, "inherit-listener"},
	{names.Config, "config"},
	{names.JSON, "json"},
	{names.Name, "name"},
	{names.DryRun, "dry-run"},
	{names.BaseImage, "base-image"},
	{names.ForceCleanOutputFolder, "force-clean-output-folder"},
	{names.GitHubOwner, "github-owner"},
	{names.GitHubRepo, "github-repo"},
	{names.IncludeFeaturesConfiguration, "include-features-configuration"},
	{names.IncludeMergedConfiguration, "include-merged-configuration"},
	{names.OmitPaths, "omit-paths"},
	{names.OutputFolder, "output-folder"},
	{names.OverrideConfig, "override-config"},
	{names.PreserveTestContainers, "preserve-test-containers"},
	{names.ProjectFolder, "project-folder"},
	{names.Registry, "registry"},
	{names.ShowDependencies, "show-dependencies"},
	{names.ShowTags, "show-tags"},
	{names.SkipScenarios, "skip-scenarios"},
	{names.Target, "target"},
	{names.TemplateArgs, "template-args"},
	{names.TemplateID, "template-id"},
	{names.Available, "available"},
	{names.Create, "create"},
	{names.FromExisting, "from-existing"},
	{names.Prerelease, "prerelease"},
	{names.ProviderSource, "provider-source"},
	{names.Use, "use"},
	{names.Version, "version"},
	{names.Channel, "channel"},
	{names.ChartPath, "chart-path"},
	{names.ChartRepo, "chart-repo"},
	{names.DisplayName, "display-name"},
	{names.Email, "email"},
	{names.Header, "header"},
	{names.HelmChartPath, "helm-chart-path"},
	{names.HelmChartVersion, "helm-chart-version"},
	{names.HelmSet, "helm-set"},
	{names.HelmValues, "helm-values"},
	{names.Host, "host"},
	{names.Insecure, "insecure"},
	{names.Instance, "instance"},
	{names.KubeContext, "kube-context"},
	{names.Login, "login"},
	{names.NoLogin, "no-login"},
	{names.NoTunnel, "no-tunnel"},
	{names.NoWait, "no-wait"},
	{names.Own, "own"},
	{names.Password, "password"},
	{names.PreventWakeup, "prevent-wakeup"},
	{names.Project, "project"},
	{names.Provider, "provider"},
	{names.ReuseValues, "reuse-values"},
	{names.ServiceAccount, "service-account"},
	{names.Token, "token"},
	{names.Upgrade, "upgrade"},
	{names.Values, "values"},
	{names.Wait, "wait"},
	{names.Address, "address"},
	{names.AuthSockID, "auth-sock-id"},
	{names.ConfigureDockerHelper, "configure-docker-helper"},
	{names.ConfigureGitHelper, "configure-git-helper"},
	{names.Container, "container"},
	{names.Daemon, "daemon"},
	{names.Docker, "docker"},
	{names.DockerArg, "docker-arg"},
	{names.DockerCommand, "docker-command"},
	{names.DockerImage, "docker-image"},
	{names.Dry, "dry"},
	{names.ExecOutputCap, "exec-output-cap"},
	{names.ExecTimeoutDefault, "exec-timeout-default"},
	{names.ExecTimeoutMax, "exec-timeout-max"},
	{names.ExtraPorts, "extra-ports"},
	{names.Fail, "fail"},
	{names.FailOnErrorCode, "fail-on-error-code"},
	{names.File, "file"},
	{names.FilterByOwner, "filter-by-owner"},
	{names.FleetWorkspaceID, "workspaceid"},
	{names.ForceBrowser, "force-browser"},
	{names.GitUserSigningKey, "git-user-signing-key"},
	{names.HelperImage, "helper-image"},
	{names.Hidden, "hidden"},
	{names.Interval, "interval"},
	{names.KeyFile, "key-file"},
	{names.MaxDepth, "max-depth"},
	{names.Namespace, "namespace"},
	{names.Port, "port"},
	{names.Request, "request"},
	{names.SingleMachine, "single-machine"},
	{names.SkipInit, "skip-init"},
	{names.SkipOnCreate, "skip-on-create"},
	{names.SkipUpdateContent, "skip-update-content"},
	{names.TargetURL, "target-url"},
	{names.Workspace, "workspace"},
	{names.WorkspaceInfo, "workspace-info"},
	{names.WorkspaceProject, "workspace-project"},
	{names.WorkspaceUID, "workspace-uid"},
}

func TestConstantWireNames(t *testing.T) {
	seen := make(map[string]struct{}, len(wireNames))
	for _, c := range wireNames {
		if c.got != c.want {
			t.Errorf("flag constant wire name = %q, want %q", c.got, c.want)
		}
		if _, dup := seen[c.got]; dup {
			t.Errorf("duplicate flag value %q shared by two constants", c.got)
		}
		seen[c.got] = struct{}{}
	}
}

func TestFlagHelpers(t *testing.T) {
	if got := names.Flag("stdio"); got != "--stdio" {
		t.Errorf("Flag = %q, want --stdio", got)
	}
	if got := names.FlagValue("log-output", "raw"); got != "--log-output=raw" {
		t.Errorf("FlagValue = %q, want --log-output=raw", got)
	}
	if got := names.FlagTrue("agent-forwarding"); got != "--agent-forwarding=true" {
		t.Errorf("FlagTrue = %q, want --agent-forwarding=true", got)
	}
	if got := names.FlagFalse("start-services"); got != "--start-services=false" {
		t.Errorf("FlagFalse = %q, want --start-services=false", got)
	}
}
