package secrets

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/devsy-org/devsy/pkg/config"
	"sigs.k8s.io/yaml"
)

const sourceConfigFileName = "secret-sources.yaml"

// SourceConfig describes an external secret source. It contains references
// only; secret values and decryption credentials are never persisted here.
type SourceConfig struct {
	Name   string `json:"name"             yaml:"name"`
	Type   string `json:"type"             yaml:"type"`
	Path   string `json:"path,omitempty"   yaml:"path,omitempty"`
	Format string `json:"format,omitempty" yaml:"format,omitempty"`
}

type sourceRegistryFile struct {
	Contexts map[string][]SourceConfig `json:"contexts,omitempty" yaml:"contexts,omitempty"`
}

func sourceConfigPath(devsyConfig *config.Config) (string, error) {
	if devsyConfig != nil && devsyConfig.Origin != "" {
		return filepath.Join(filepath.Dir(devsyConfig.Origin), sourceConfigFileName), nil
	}
	configPath, err := config.GetConfigPath()
	if err != nil {
		return "", err
	}
	return filepath.Join(filepath.Dir(configPath), sourceConfigFileName), nil
}

// LoadSourceConfigs loads external sources registered for the active context.
func LoadSourceConfigs(devsyConfig *config.Config) ([]SourceConfig, error) {
	filePath, err := sourceConfigPath(devsyConfig)
	if err != nil {
		return nil, err
	}
	registry, err := loadSourceRegistry(filePath)
	if err != nil {
		return nil, err
	}
	if registry.Contexts == nil || devsyConfig == nil {
		return nil, nil
	}
	items := registry.Contexts[devsyConfig.DefaultContext]
	return append([]SourceConfig(nil), items...), nil
}

// SaveSourceConfigs writes external source metadata for the active context.
func SaveSourceConfigs(devsyConfig *config.Config, sources []SourceConfig) error {
	if devsyConfig == nil {
		return fmt.Errorf("devsy config is nil")
	}
	filePath, err := sourceConfigPath(devsyConfig)
	if err != nil {
		return err
	}
	registry, err := loadSourceRegistry(filePath)
	if err != nil {
		return err
	}
	setContextSources(&registry, devsyConfig.DefaultContext, sources)
	return writeSourceRegistry(filePath, registry)
}

func loadSourceRegistry(filePath string) (sourceRegistryFile, error) {
	registry := sourceRegistryFile{Contexts: map[string][]SourceConfig{}}
	// #nosec G304 -- filePath is generated by sourceConfigPath under Devsy's config directory.
	data, err := os.ReadFile(filePath)
	if os.IsNotExist(err) {
		return registry, nil
	}
	if err != nil {
		return registry, fmt.Errorf("read secret source config: %w", err)
	}
	if err := yaml.Unmarshal(data, &registry); err != nil {
		return registry, fmt.Errorf("parse secret source config: %w", err)
	}
	if registry.Contexts == nil {
		registry.Contexts = map[string][]SourceConfig{}
	}
	return registry, nil
}

func setContextSources(registry *sourceRegistryFile, contextName string, sources []SourceConfig) {
	if registry.Contexts == nil {
		registry.Contexts = map[string][]SourceConfig{}
	}
	if len(sources) == 0 {
		delete(registry.Contexts, contextName)
		return
	}
	registry.Contexts[contextName] = append([]SourceConfig(nil), sources...)
}

func writeSourceRegistry(filePath string, registry sourceRegistryFile) error {
	data, err := yaml.Marshal(registry)
	if err != nil {
		return fmt.Errorf("marshal secret source config: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(filePath), 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(filePath, data, 0o600); err != nil {
		return fmt.Errorf("write secret source config: %w", err)
	}
	return nil
}

func FindSourceConfig(sources []SourceConfig, name string) (SourceConfig, bool) {
	for _, source := range sources {
		if source.Name == name {
			return source, true
		}
	}
	return SourceConfig{}, false
}

func AddSourceConfig(sources []SourceConfig, source SourceConfig) ([]SourceConfig, error) {
	if err := ValidateSourceName(source.Name); err != nil {
		return nil, err
	}
	if source.Name == LocalSourceName {
		return nil, fmt.Errorf("secret source name %q is reserved", LocalSourceName)
	}
	if _, exists := FindSourceConfig(sources, source.Name); exists {
		return nil, fmt.Errorf("secret source %q already exists", source.Name)
	}
	return append(append([]SourceConfig(nil), sources...), source), nil
}

func RemoveSourceConfig(sources []SourceConfig, name string) ([]SourceConfig, bool) {
	for i, source := range sources {
		if source.Name != name {
			continue
		}
		out := append([]SourceConfig(nil), sources[:i]...)
		out = append(out, sources[i+1:]...)
		return out, true
	}
	return append([]SourceConfig(nil), sources...), false
}
