package secrets

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/devsy-org/devsy/pkg/config"
	"sigs.k8s.io/yaml"
)

const sourceConfigFileName = "secret-sources.yaml"

// SourceConfig describes an external secret source. It contains references
// only; secret values and decryption credentials are never persisted here.
type SourceConfig struct {
	Name   string `json:"name"             yaml:"name"`
	Type   string `json:"type"             yaml:"type"`
	Path   string `json:"path,omitempty"   yaml:"path,omitempty"`
	Format string `json:"format,omitempty" yaml:"format,omitempty"`
}

type sourceRegistryFile struct {
	Contexts map[string][]SourceConfig `json:"contexts,omitempty" yaml:"contexts,omitempty"`
}

func sourceConfigPath(devsyConfig *config.Config) (string, error) {
	if devsyConfig != nil && devsyConfig.Origin != "" {
		return filepath.Join(filepath.Dir(devsyConfig.Origin), sourceConfigFileName), nil
	}
	configPath, err := config.GetConfigPath()
	if err != nil {
		return "", err
	}
	return filepath.Join(filepath.Dir(configPath), sourceConfigFileName), nil
}

// LoadSourceConfigs loads external sources registered for the active context.
func LoadSourceConfigs(devsyConfig *config.Config) ([]SourceConfig, error) {
	filePath, err := sourceConfigPath(devsyConfig)
	if err != nil {
		return nil, err
	}
	registry, err := loadSourceRegistry(filePath)
	if err != nil {
		return nil, err
	}
	if registry.Contexts == nil || devsyConfig == nil {
		return nil, nil
	}
	items := registry.Contexts[devsyConfig.DefaultContext]
	return append([]SourceConfig(nil), items...), nil
}

// ModifySourceConfigs serializes external source modifications across processes
// by holding the secret-sources lock while loading, mutating, and writing configuration.
func ModifySourceConfigs(
	devsyConfig *config.Config,
	mutate func(sources []SourceConfig) ([]SourceConfig, error),
) error {
	if devsyConfig == nil {
		return fmt.Errorf("devsy config is nil")
	}
	filePath, err := sourceConfigPath(devsyConfig)
	if err != nil {
		return err
	}
	unlock, err := acquireFlock(filepath.Dir(filePath), sourceConfigFileName+".lock")
	if err != nil {
		return err
	}
	defer unlock()
	registry, err := loadSourceRegistry(filePath)
	if err != nil {
		return err
	}
	var current []SourceConfig
	if registry.Contexts != nil {
		current = registry.Contexts[devsyConfig.DefaultContext]
	}
	updated, err := mutate(append([]SourceConfig(nil), current...))
	if err != nil {
		return err
	}
	setContextSources(&registry, devsyConfig.DefaultContext, updated)
	return writeSourceRegistry(filePath, registry)
}

// SaveSourceConfigs writes external source metadata for the active context.
func SaveSourceConfigs(devsyConfig *config.Config, sources []SourceConfig) error {
	return ModifySourceConfigs(devsyConfig, func(_ []SourceConfig) ([]SourceConfig, error) {
		return sources, nil
	})
}

func loadSourceRegistry(filePath string) (sourceRegistryFile, error) {
	registry := sourceRegistryFile{Contexts: map[string][]SourceConfig{}}
	// #nosec G304 -- filePath is generated by sourceConfigPath under Devsy's config directory.
	data, err := os.ReadFile(filePath)
	if os.IsNotExist(err) {
		return registry, nil
	}
	if err != nil {
		return registry, fmt.Errorf("read secret source config: %w", err)
	}
	if err := yaml.Unmarshal(data, &registry); err != nil {
		return registry, fmt.Errorf("parse secret source config: %w", err)
	}
	if registry.Contexts == nil {
		registry.Contexts = map[string][]SourceConfig{}
	}
	return registry, nil
}

func setContextSources(registry *sourceRegistryFile, contextName string, sources []SourceConfig) {
	if registry.Contexts == nil {
		registry.Contexts = map[string][]SourceConfig{}
	}
	if len(sources) == 0 {
		delete(registry.Contexts, contextName)
		return
	}
	registry.Contexts[contextName] = append([]SourceConfig(nil), sources...)
}

func writeSourceRegistry(filePath string, registry sourceRegistryFile) error {
	data, err := yaml.Marshal(registry)
	if err != nil {
		return fmt.Errorf("marshal secret source config: %w", err)
	}
	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	tmpName, err := createTempSourceRegistry(dir, data)
	if err != nil {
		return err
	}
	return replaceSourceRegistry(tmpName, filePath, dir)
}

func createTempSourceRegistry(dir string, data []byte) (string, error) {
	tmpFile, err := os.CreateTemp(dir, sourceConfigFileName+".tmp-*")
	if err != nil {
		return "", fmt.Errorf("create temp secret source config: %w", err)
	}
	tmpName := tmpFile.Name()
	var success bool
	defer func() {
		_ = tmpFile.Close()
		if !success {
			_ = os.Remove(tmpName)
		}
	}()
	if err := tmpFile.Chmod(0o600); err != nil {
		return "", fmt.Errorf("chmod temp secret source config: %w", err)
	}
	if _, err := tmpFile.Write(data); err != nil {
		return "", fmt.Errorf("write temp secret source config: %w", err)
	}
	if err := tmpFile.Sync(); err != nil {
		return "", fmt.Errorf("sync temp secret source config: %w", err)
	}
	success = true
	return tmpName, nil
}

func replaceSourceRegistry(tmpName, filePath, dir string) error {
	defer func() { _ = os.Remove(tmpName) }()
	if err := os.Rename(tmpName, filePath); err != nil {
		return fmt.Errorf("replace secret source config: %w", err)
	}
	// #nosec G304 -- dir is filepath.Dir(filePath) under Devsy's config directory.
	if d, err := os.Open(dir); err == nil {
		_ = d.Sync()
		_ = d.Close()
	}
	return nil
}

func FindSourceConfig(sources []SourceConfig, name string) (SourceConfig, bool) {
	for _, source := range sources {
		if source.Name == name {
			return source, true
		}
	}
	return SourceConfig{}, false
}

func AddSourceConfig(sources []SourceConfig, source SourceConfig) ([]SourceConfig, error) {
	if err := ValidateSourceName(source.Name); err != nil {
		return nil, err
	}
	if source.Name == LocalSourceName {
		return nil, fmt.Errorf("secret source name %q is reserved", LocalSourceName)
	}
	if _, exists := FindSourceConfig(sources, source.Name); exists {
		return nil, fmt.Errorf("secret source %q already exists", source.Name)
	}
	return append(append([]SourceConfig(nil), sources...), source), nil
}

func RemoveSourceConfig(sources []SourceConfig, name string) ([]SourceConfig, bool) {
	for i, source := range sources {
		if source.Name != name {
			continue
		}
		out := append([]SourceConfig(nil), sources[:i]...)
		out = append(out, sources[i+1:]...)
		return out, true
	}
	return append([]SourceConfig(nil), sources...), false
}
