name: Devcontainer

on:
  push:
    branches: [main]
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer.yml"
  pull_request:
    branches: [main]
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer.yml"
  workflow_dispatch:
    inputs:
      runCmd:
        description: "Command to run inside the devcontainer"
        required: false
        default: test -x "$(command -v prek)"

permissions:
  contents: read

env:
  DEFAULT_RUN_CMD: test -x "$(command -v prek)"

jobs:
  build:
    name: Build and Run Devcontainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "latest"

      - uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          runCmd: ${{ inputs.runCmd || env.DEFAULT_RUN_CMD }}
